<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0 static/glbs/Computer.glb
-->

<script>
	import { T } from '@threlte/core';
	import { useGltf } from '@threlte/extras';

	let { fallback, error, children, ref = $bindable(), ...props } = $props();

	const gltf = useGltf('glbs/Computer.glb');
</script>

<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Mesh
			geometry={gltf.nodes.Computer.geometry}
			material={gltf.materials.FinalComputer}
			position={[0.0, 0.5, 0.45]}
			rotation={[-0.11, 0.35, 0]}
			scale={1.4}
		/>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
